import { ItemRoomSearch } from "../interfaces/generalInterfaces";

export const LIST_ROOMS_TO_HOTEL: ItemRoomSearch[] = [
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=1",
    title_hotel: "Hotel Dann Cartagena",
    number_guests: 2,
    number: 71737,
    type: "officiis",
    description: "Qui velit nihil incidunt quam iusto laudantium sequi placeat.",
    created_at: "2097-10-22T11:03:41.982Z",
    available: true,
    base_price: "985.00",
    tax: "357.00",
    address: "47291 Stehr Fall",
    city: "Cartagena",
    id: "1",
    hotel_id: "1"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=2",
    title_hotel: "JW Marriott Hotel Bogotá",
    number_guests: 3,
    number: 77997,
    type: "velites",
    description: "Fugiat dignissimos qui dolores enim.",
    created_at: "2031-07-02T00:11:08.198Z",
    available: true,
    base_price: "922.00",
    tax: "285.00",
    address: "50747 Ledner Path",
    city: "Bogotá",
    id: "2",
    hotel_id: "2"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=3",
    title_hotel: "Movich Hotel de Pereira",
    number_guests: 2,
    number: 2629,
    type: "quas",
    description: "Similique repellendus delectus saepe.",
    created_at: "2054-05-22T14:09:52.375Z",
    available: true,
    base_price: "715.00",
    tax: "709.00",
    address: "0129 Wilbert Parks",
    city: "Pereira",
    id: "3",
    hotel_id: "3"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=5",
    title_hotel: "Hilton Cartagena",
    number_guests: 2,
    number: 28760,
    type: "labore",
    description: "Reiciendis ad quod soluta.",
    created_at: "2016-10-23T09:26:13.493Z",
    available: false,
    base_price: "171.00",
    tax: "266.00",
    address: "65289 Karine Mountains",
    city: "Cartagena",
    id: "4",
    hotel_id: "4"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=6",
    title_hotel: "Hotel Estelar Milla de Oro",
    number_guests: 5,
    number: 23369,
    type: "officiis",
    description: "Numquam quod mollitia corrupti nisi blanditiis quos quae est sed.",
    created_at: "2079-10-17T00:08:25.157Z",
    available: true,
    base_price: "612.00",
    tax: "660.00",
    address: "079 Schultz Well",
    city: "Medellín",
    id: "5",
    hotel_id: "1"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=7",
    title_hotel: "Hotel Dann Carlton",
    number_guests: 3,
    number: "77998",
    type: "Suite",
    description: "Comfortable, bathroom and parking",
    created_at: "",
    available: true,
    base_price: "930.00",
    tax: "285.00",
    address: "always live street",
    city: "Cali",
    id: "6",
    hotel_id: "2"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=8",
    title_hotel: "Hotel Diez",
    number_guests: 1,
    number: "337",
    type: "Non et iusto impedit",
    description: "Dolores aut animi l",
    created_at: "",
    available: true,
    base_price: "975",
    tax: "3",
    address: "Quis earum est in l",
    city: "Medellín",
    id: "7",
    hotel_id: "1"
  },
  {
    image: "https://loremflickr.com/640/480?random9",
    title_hotel: "Hotel NH Collection Royal Smartsuites",
    number_guests: 2,
    number: 59854,
    type: "nisi",
    description: "Tempora aperiam expedita consequatur nemo corporis cupiditate ea eos ipsa.",
    created_at: "2094-11-24T14:32:25.369Z",
    available: false,
    base_price: "335.00",
    tax: "56.00",
    address: "435 Luettgen Stravenue",
    city: "Bogotá",
    id: "8",
    hotel_id: "1"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=10",
    title_hotel: "GHL Hotel Capital",
    number_guests: 1,
    number: 65197,
    type: "asperiores",
    description: "Earum eligendi alias praesentium cupiditate eius placeat commodi fuga.",
    created_at: "2046-10-21T02:05:52.950Z",
    available: true,
    base_price: "261.00",
    tax: "718.00",
    address: "906 Fadel Villages",
    city: "Bogotá",
    id: "9",
    hotel_id: "2"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=11",
    title_hotel: "Casa Dann Carlton Hotel & SPA",
    number_guests: 2,
    number: 90422,
    type: "reprehenderit",
    description: "Nam eveniet et reiciendis amet impedit alias aliquam saepe.",
    created_at: "2002-10-09T07:44:27.131Z",
    available: false,
    base_price: "679.00",
    tax: "272.00",
    address: "553 Hodkiewicz Oval",
    city: "Bogotá",
    id: "10",
    hotel_id: "3"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=12",
    title_hotel: "Hotel Dann Cartagena",
    number_guests: 4,
    number: 47627,
    type: "rerum",
    description: "Laborum impedit eos.",
    created_at: "2033-01-13T19:13:27.758Z",
    available: true,
    base_price: "906.00",
    tax: "456.00",
    address: "970 Smith Walk",
    city: "Cartagena",
    id: "11",
    hotel_id: "4"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=13",
    title_hotel: "San Fernando Plaza Hotel",
    number_guests: 2,
    number: 72762,
    type: "laboriosam",
    description: "Magnam eligendi pariatur.",
    created_at: "2055-02-23T09:58:04.969Z",
    available: false,
    base_price: "115.00",
    tax: "105.00",
    address: "0575 Dach Mills",
    city: "Medellín",
    id: "12",
    hotel_id: "1"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=14",
    title_hotel: "Hotel Dann Cartagena",
    number_guests: 5,
    number: 41045,
    type: "minus",
    description: "Aperiam eos ab pariatur.",
    created_at: "2033-07-24T09:10:26.987Z",
    available: true,
    base_price: "117.00",
    tax: "635.00",
    address: "8747 Alejandrin Skyway",
    city: "Cartagena",
    id: "13",
    hotel_id: "2"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=15",
    title_hotel: "NH Collection Bogotá Andino Royal",
    number_guests: 2,
    number: 60712,
    type: "rem",
    description: "Suscipit ipsa quo quaerat occaecati exercitationem a.",
    created_at: "2099-09-12T05:28:52.027Z",
    available: false,
    base_price: "186.00",
    tax: "28.00",
    address: "3207 Tianna Skyway",
    city: "Bogotá",
    id: "14",
    hotel_id: "3"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=16",
    title_hotel: "Hotel Dann Cartagena",
    number_guests: 2,
    number: 98168,
    type: "veritatis",
    description: "Quis a quam voluptates maiores dolore doloremque.",
    created_at: "2036-10-11T21:34:38.756Z",
    available: false,
    base_price: "887.00",
    tax: "588.00",
    address: "86177 Gottlieb Light",
    city: "Cartagena",
    id: "15",
    hotel_id: "4"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=17",
    title_hotel: "Hotel Dann Carlton Bucaramanga",
    number_guests: 3,
    number: 35395,
    type: "tempora",
    description: "Enim necessitatibus officiis reiciendis.",
    created_at: "2075-05-24T05:56:31.061Z",
    available: true,
    base_price: "398.00",
    tax: "886.00",
    address: "69160 Nelson Road",
    city: "Bucaramanga",
    id: "16",
    hotel_id: "1"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=18",
    title_hotel: "Hotel Dann Cartagena",
    number_guests: 2,
    number: 6275,
    type: "maiores",
    description: "Ipsa quo pariatur.",
    created_at: "2076-02-18T13:42:12.873Z",
    available: true,
    base_price: "935.00",
    tax: "273.00",
    address: "18702 Walsh Road",
    city: "Cartagena",
    id: "17",
    hotel_id: "2"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=19",
    title_hotel: "Hotel Estelar Miraflores",
    number_guests: 2,
    number: 37622,
    type: "est",
    description: "Quaerat repellat laboriosam repudiandae quam.",
    created_at: "2043-10-11T07:59:06.333Z",
    available: true,
    base_price: "419.00",
    tax: "426.00",
    address: "35043 Edmund Wall",
    city: "Lima",
    id: "18",
    hotel_id: "3"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=20",
    title_hotel: "Hotel Dann Cartagena",
    number_guests: 4,
    number: 81013,
    type: "iure",
    description: "Accusantium eius vitae.",
    created_at: "2041-03-26T06:46:58.742Z",
    available: false,
    base_price: "210.00",
    tax: "147.00",
    address: "381 Derick Oval",
    city: "Cartagena",
    id: "19",
    hotel_id: "4"
  },
  {
    image: "https://loremflickr.com/640/480/brazil,rio?random=21",
    title_hotel: "Hotel Estelar La Fontana",
    number_guests: 2,
    number: 9213,
    type: "eveniet",
    description: "Tempora magni dolorem odio iste expedita facilis facilis architecto.",
    created_at: "2038-12-08T07:06:04.411Z",
    available: true,
    base_price: "938.00",
    tax: "583.00",
    address: "707 Vandervort Dale",
    city: "Bogotá",
    id: "20",
    hotel_id: "1"
  }
];